stages:
  - changelog-draft

.generate_changelog_common:
  image: alpine:latest
  before_script:
    - apk add --no-cache git git-cliff
    - echo "📦 Tool Versions:"
    - git --version
    - git-cliff --version

    - set -euo pipefail
    # Configuration variables
    - CLIFF_CONFIG_PATH=".gitlab/ci/config/.cliff.toml"

generate_changelog_draft:
  stage: changelog-draft
  extends: .generate_changelog_common
  script:
    - echo "📝 Generating changelog draft..."

    # Ensure .cliff.toml exists (fail fast)
    - |
      if [ ! -f "$CLIFF_CONFIG_PATH" ]; then
        echo "❌ $CLIFF_CONFIG_PATH not found. Aborting."
        exit 1
      fi

    # Fetch main branch for comparison
    - echo "📥 Fetching origin/main..."
    - git fetch origin main

    # Generate changelog draft
    - git-cliff --unreleased --config $CLIFF_CONFIG_PATH > .changelog_draft.md
    - echo "✅ Draft generated at .changelog_draft.md"
    - echo "📌 Please review the draft changelog."
  artifacts:
    name: "changelog-draft"
    paths:
      - .changelog_draft.md
    expire_in: 1 week

  rules:
    # Execute only if:
    # 1. It's a merge request
    # 2. The source branch is feature/*
    # 3. .cliff.toml exists
    - if: "$CI_MERGE_REQUEST_IID"
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
      when: on_success
    - exists:
        - "$CLIFF_CONFIG_PATH"
      when: on_success
    # Skip this job unless all conditions above are satisfied
    - when: never

generate_changelog_release:
  stage: changelog
  image: alpine:latest
  before_script:
    - apk add --no-cache git git-cliff
  script:
    - echo "📝 Generating final changelog...
    - |
      if [ ! -f "$CLIFF_CONFIG_PATH" ]; then
        echo "❌ $CLIFF_CONFIG_PATH not found. Aborting."
        exit 1
      fi
    - git fetch origin main
    - git-cliff --config $CLIFF_CONFIG_PATH  > CHANGELOG.md
    - echo "✅ Final changelog generated at CHANGELOG.md"
    - echo "📌 Please review the final changelog."
  artifacts:
    name: "changelog-release"
    paths:
      - CHANGELOG.md
    expire_in: 1 week
  rules:
    # - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
    when: manual

merge_changelog_unreleased:
  stage: changelog
  extends: .default_before_script
  script:
    - echo "📝 Merging changelog draft into CHANGELOG.md..."
    - bash .gitlab/ci/scripts/merge_draft_into_changelog.sh
    - git add CHANGELOG.md
    - git commit -m "docs: update changelog"
    - git push origin "$CI_COMMIT_BRANCH"
    - echo "✅ Changelog merged into CHANGELOG.md"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - exists:
        - .changelog_draft.md
        - CHANGELOG.md
