stages:
  - split

variables:
  PACKAGE_DIR: "Assets/UserPackage"
  # The URL of the target repository where the UPM package will be pushed.
  # Expected format: HTTPS URL (e.g., https://gitlab.local/group/project.git)
  TARGET_REPO_URL: "${TARGET_REPO_URL:-https://gitlab.local/linesimulation/unity-npm/mypackage.git}"
  # Personal Access Token or Project Access Token with write_repository scope
  CI_PUSH_TOKEN: "<your_personal_access_token_here>"
  # Replace <your_personal_access_token_here> with a Personal Access Token or Project Access Token
  # that has the 'write_repository' scope. You can generate this token in your GitLab account settings.

  # Git configuration for the CI user
  CI_USER_NAME: "GitLab CI"
  CI_EMAIL: "ci@example.com"

split_upm_package:
  stage: split
  image: alpine:latest
  before_script:
    - echo "📦 Split UPM package..."
    -
    - echo "🔧 Configuring Git..."
    - git config --global user.name "$CI_USER_NAME"
    - git config --global user.email "$CI_EMAIL"
    -
    - echo "✂️ Split UPM package from main branch..."
    - git subtree split --prefix=$PACKAGE_DIR -b extracted-branch
    -
    - echo "🔗 Adding remote repository..."
    - |
      echo "🔍 Checking access to remote repository..."
      if git ls-remote https://oauth2:${CI_PUSH_TOKEN}@${TARGET_REPO_URL#https://} &>/dev/null; then
        echo "✅ Remote repository is accessible. Proceeding to push."
      else
        echo "❌ Cannot access remote repository or it does not exist."
        exit 1
      fi
    -
    - echo "🚀 Pushing subtree to main branch..."
    - git push -f https://oauth2:${CI_PUSH_TOKEN}@${TARGET_REPO_URL#https://} extracted-branch:main
    -
    - echo "✅ UPM package split and pushed successfully."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
