[changelog]
header = "# Changelog"
body = """
{% if version %}## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits %}
- {{ commit.message | split(pat="\\n") | first }}{% endfor %}
{% endfor %}
"""
footer = ""

[git]
tag_pattern = "^v?[0-9]+\\.[0-9]+\\.[0-9]+$"
skip_unreleased = false
ignore_tag_error = true
filter_commits = true
commit_filters = [{ message = "^Merge", exclude = true }]

[commit_types]
feat = { group = "Features" }
fix = { group = "Bug Fixes" }
docs = { group = "Documentation" }
refactor = { group = "Refactoring" }
chore = { group = "Maintenance" }
test = { group = "Testing" }
ci = { group = "CI" }
perf = { group = "Performance" }
style = { group = "Style" }
