stages:
  - fetch
  - prepare
  - update
  - draft
  - release

variables:
  CLIFF_CONFIG_PATH: "${CI_PROJECT_DIR}/.gitlab/ci/config/.cliff.toml"
  CHANGELOG_FILE: "CHANGELOG.md"

include:
  - project: "line-simulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/npm/npm-publish.yml"
  - project: "line-simulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/release/project-release.yml"
  - project: "line-simulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/changelog/draft-changelog.yml"
  - project: "line-simulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/changelog/release-changelog.yml"

workflow:
  rules:
    # When a pipeline is triggered by a schedule, run the pipeline.
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    # When a merge request is created or updated, run the pipeline.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    # When pushing to the default branch, run the pipeline.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    # Otherwise, do not run the pipeline.
    - when: never
