stages:
  - fetch
  - prepare
  - draft
  - update
  - release

variables:
  CLIFF_CONFIG_PATH: "${CI_PROJECT_DIR}/.gitlab/ci/config/.cliff.toml"
  CHANGELOG_FILE: "CHANGELOG.md"

include:
  - project: "LineSimulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/fetch/fetch-ci.yml"
  - project: "LineSimulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/changelog/common.yml"
  - project: "LineSimulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/npm/npm-publish.yml"
  - project: "LineSimulation/unity-npm/ci-scripts"
    ref: "feature/add-ci-templates"
    file: "/.gitlab/ci/templates/release/project-release.yml"

changelog:
  stage: update
  script:
    - scripts/changelog/update_for_release.sh
  only:
    refs:
      - main

release:
  stage: release
  script:
    - scripts/release/manage_version.sh
  only:
    refs:
      - tags
