# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""

body = """
{%- macro remote_url() -%}
  https://gitlab.example.local/group/repo
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | upper_first }}
  {%- for commit in commits %}
    {%- set msg = commit.message | split(pat="\n") | first | trim -%}
    {%- set pr_match = msg | regex_search(pattern="!([0-9]+)") -%}
    {%- set issue_match = msg | regex_search(pattern="#([0-9]+)") -%}

    - {{ msg | upper_first }}\
      {%- if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
      {%- if pr_match %}
        in [!{{ pr_match.1 }}]({{ self::remote_url() }}/-/merge_requests/{{ pr_match.1 }})
      {%- elif issue_match %}
        in [#{{ issue_match.1 }}]({{ self::remote_url() }}/-/issues/{{ issue_match.1 }})
      {%- endif %}
  {% endfor %}
{% endfor %}

{%- if gitlab.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## New Contributors
{%- endif -%}

{% for contributor in gitlab.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [!{{ contributor.pr_number }}]({{ self::remote_url() }}/-/merge_requests/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor %}\n
"""

footer = """
{%- macro remote_url() -%}
  https://gitlab.example.local/group/repo
{%- endmacro -%}

{% for release in releases -%}
  {% if release.version -%}
    {% if release.previous.version -%}
      [{{ release.version | trim_start_matches(pat="v") }}]: \
        {{ self::remote_url() }}/-/compare/{{ release.previous.version }}...{{ release.version }}
    {% endif -%}
  {% else -%}
    [unreleased]: {{ self::remote_url() }}/-/compare/{{ release.previous.version }}...HEAD
  {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false

# commitメッセージ前処理（番号除去せず、リンク出力に使うため空）
commit_preprocessors = []

# Conventional Commits に準拠した commit type → group mapping
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^docs", group = "Documentation" },
    { message = "^style", group = "Styling" },
    { message = "^refactor", group = "Changed" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Tests" },
    { message = "^build", group = "Build" },
    { message = "^ci", group = "CI" },
    { message = "^chore", group = "Chore" },
    { message = "^revert", group = "Revert" },
]

filter_commits = false
topo_order = false
sort_commits = "newest"
