# Title: project-release.yml
#
# Description:
# This script is designed to create a release for your project on GitLab.
# It is used in a GitLab CI/CD pipeline.
# It consists of four main stages:
#     1. bump: Bump the version
#     2. changelog: Update the changelog
#     3. release: Create the release
#
# Features:
#     - Automatically update the version based on the VERSION.yml file.
#     - Automatically increment the version by comparing it with the already released version in the GitLab Releases.
#     - Create a release on GitLab with the new version number.
#     - Tag the commit with the new version number.

stages:
  - bump
  - changelog
  - release

variables:
  GIT_AUTHOR_NAME: "gitlab-ci"
  GIT_AUTHOR_EMAIL: "ci@example.com"
  VERSION_FILE: "VERSION.yml"

.default_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    # Install necessary tools
    - apk add --no-cache git bash yq
    - |
      echo "📦 Tool Versions:"
    - git --version
    - bash --version
    - release-cli --version
    - yq --version

    # set -euo pipefail: Exit immediately if a command exits with a non-zero status.
    - set -euo pipefail
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"

.default_rules:
  rules:
    # This job will run only on the default branch (e.g., main or master).
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    # This job will run manually for other branches.
    - when: manual

bump_version:
  # This stage is responsible for bumping the version of the project.
  # It uses a script to read the VERSION.yml file and update the version accordingly.
  # The script also creates a .next_version file that contains the new version number.
  # The .next_version file is used in the changelog stage to update the changelog.
  # The script also commits the changes to the VERSION.yml file and pushes them to the repository.
  stage: bump
  extends:
    - .default_job
    - .default_rules
  script:
    - echo "🔍 Checking for $VERSION_FILE"
    - bash .gitlab/ci/scripts/release/manage_version.sh $VERSION_FILE
    - echo "✅ Bumped version to $(cat .next_version)"
  artifacts:
    name: "next_version"
    paths:
      - .next_version

update_changelog:
  # This stage is responsible for updating the changelog.
  # It uses a script to read the .next_version file and update the changelog accordingly.
  # The script also commits the changes to the CHANGELOG.md file and pushes them to the repository.
  stage: changelog
  extends:
    - .default_job
    - .default_rules
  needs:
    - bump_version
  script:
    - VERSION=$(cat .next_version)
    - |
      echo "🚀 Updating changelog for version: $VERSION"

    # Update CHANGELOG.md
    - bash .gitlab/ci/scripts/changelog/update_for_release.sh "$VERSION" "$CHANGELOG_FILE"

    # Commit and push the updated changelog
    - echo "📦 Committing changes..."
    - git add $CHANGELOG_FILE
    - |
      git commit -m "docs: update changelog for tag $VERSION [ci skip]"
    - git push -o ci.skip origin HEAD:$CI_COMMIT_REF_NAME --force-with-lease
    - echo "🚀 Changelog updated successfully for version $VERSION"
  artifacts:
    name: "next_version"
    paths:
      - .next_version

create_release:
  # This stage is responsible for creating a release on GitLab.
  # It uses the release-cli tool to create a release with the new version number.
  # The release is created with the tag name and description from the CHANGELOG.md file.
  # The release is created only when a tag is created.
  # The release is created with the new version number and the changelog as the description.
  stage: release
  extends:
    - .default_job
    - .default_rules
  needs:
    - bump_version
    - update_changelog
  script:
    - VERSION=$(cat .next_version)
    - echo "🚀 Creating release for version: v$VERSION"
    # Check if the release already exists
    - |
      if git rev-parse --verify "v$VERSION" >/dev/null 2>&1; then
        echo "🚫 Release v$VERSION already exists. Skipping release creation."
        exit 0
      fi
    # Generate release notes from CHANGELOG.md
    - bash .gitlab/ci/scripts/release/generate_release_note.sh "$CHANGELOG_FILE" ".release_note"
    - echo "📦 Creating release description..."
    - echo "Release notes for v$VERSION" > .release_description
    - printf "\n---\n" >> .release_description
    - cat .release_note >> .release_description
    # Tag the commit with the new version number
    - |
      echo "🏷️ Tagging: v$VERSION"
    - git tag "v$VERSION"
    - git push -o ci.skip origin "v$VERSION"
    # Create the release on GitLab
    # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    - echo "🚀 Creating release on GitLab..."
    - release-cli create \
      --name "v$VERSION" \
      --tag-name "v$VERSION" \
      --description-file ./.release_description
    - echo "✅ Release created successfully for version v$VERSION"
  artifacts:
    reports:
      release: .release_description
    expire_in: 1 day
