# Title: changelog/draft.yml
#
# Description:
# This script is designed to generate a draft changelog using git-cliff.
# It is used in a GitLab CI/CD pipeline.
# It consists of one main stage:
#     1. draft: Generate a draft changelog.
#
# Features:
#     - Generates a draft changelog based on commit messages using git-cliff.
#     - The draft is generated in the .changelog_draft.md file.
#     - The draft is generated only for merge requests and feature branches.
#     - The draft is generated only if the .cliff.toml file exists.
#     - The draft is generated only if the job is triggered manually or automatically.

include:
  - local: ".gitlab/ci/templates/changelog/common.yml"

stages:
  - draft

generate_changelog_draft:
  stage: draft
  extends: .default_before_script
  script:
    - echo "📝 Generating changelog draft..."

    # Ensure .cliff.toml exists (fail fast).
    - |
      if [ ! -f "$CLIFF_CONFIG_PATH" ]; then
        echo "❌ $CLIFF_CONFIG_PATH not found. Aborting."
        exit 1
      fi

    # Fetch main branch for comparison.
    - echo "📥 Fetching origin/main..."
    - git fetch --depth=0 origin main

    # Generate Unreleased draft changelog.
    # NOTE: --prepend is used to prepend the changelog draft to the existing CHANGELOG.md file.
    - git-cliff \
      --unreleased \
      --config $CLIFF_CONFIG_PATH \
      --prepend \
      "$CHANGELOG_FILE"
    - echo "📜 Changelog draft generated in $CHANGELOG_FILE."

    # Commit & push updated CHANGELOG.md.
    - |
      if git diff --quiet $CHANGELOG_FILE; then
        echo "ℹ️ No changes in $CHANGELOG_FILE, skipping commit."
        exit 0
      fi
    - echo "📦 Committing changes..."
    - git add $CHANGELOG_FILE
    - |
      git commit -m "docs: update changelog draft [ci skip]"
    - |
      git push -o ci.skip origin HEAD:$CI_COMMIT_REF_NAME
    - echo "📦 Pushed changes to $CI_COMMIT_REF_NAME."
    - echo "✅ Changelog draft committed successfully."
    - echo "📌 Please review the draft changelog."
  rules:
    # Execute only if:
    # 1. It's a merge request
    # 2. The source branch is feature/*
    # 3. .cliff.toml exists
    - if: "$CI_MERGE_REQUEST_IID"
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
      when: on_success
    - exists:
        - "$CLIFF_CONFIG_PATH"
      when: on_success
    # Manual trigger for other branches.
    - when: manual
    # Skip this job unless all conditions above are satisfied.
    - when: never
