# Title: changelog/merge.yml
#
# Description:
# This script is designed to merge a changelog draft into CHANGELOG.md.
# It is used in a GitLab CI/CD pipeline.
# It consists of one main stage:
#     1. merge: Merge the changelog draft into CHANGELOG.md.
#
# Features:
#     - Merges the draft changelog into CHANGELOG.md.
#     - Commits and pushes the updated CHANGELOG.md to the current branch.
#     - Runs only if the draft changelog exists and the pipeline is triggered by a merge request event.
#     - Can be manually triggered for other branches.

include:
  - local: ".gitlab/ci/templates/changelog/common.yml"

stages:
  - merge

merge_changelog_draft:
  stage: merge
  extends: .default_before_script
  script:
    - echo "📝 Merging changelog draft into CHANGELOG.md..."

    # Merge the draft into CHANGELOG.md
    - bash .gitlab/ci/scripts/changelog/merge.sh

    # Commit & push updated CHANGELOG.md
    - git add CHANGELOG.md
    - git commit -m "docs: update changelog"
    - git push origin "$CI_COMMIT_BRANCH"
    - echo "✅ Changelog merged into CHANGELOG.md"
  rules:
    # Execute only if:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PIPELINE_SOURCE'
      exists:
        - .changelog_draft.md
      when: on_success
    # Manual trigger for other branches
    - when: manual
    # Skip otherwise
    - when: never
