# Title: changelog/release.yml
#
# Description:
# This script is designed to generate and manage changelogs using git-cliff.
# It is used in a GitLab CI/CD pipeline.
# It consists of one main stage:
#     1. release: Generate the final changelog.
#
# Features:
#     - Generates a final changelog for the release using git-cliff.

include:
  - local: ".gitlab/ci/templates/changelog/common.yml"

stages:
  - release

generate_changelog_release:
  stage: release
  extends: .default_before_script
  script:
    - echo "📝 Generating final changelog..."

    - |
      if [ ! -f "$CLIFF_CONFIG_PATH" ]; then
        echo "❌ $CLIFF_CONFIG_PATH not found. Aborting."
        exit 1
      fi

    # Fetch main branch for comparison
    - echo "📥 Fetching origin/main..."
    - git fetch origin main

    # Generate final changelog
    - git-cliff --config $CLIFF_CONFIG_PATH  > $CHANGELOG_FILE
    - echo "✅ Final changelog generated at $CHANGELOG_FILE"
    - echo "📌 Please review the final changelog."
  artifacts:
    name: "changelog-release"
    paths:
      - CHANGELOG.md
    expire_in: 1 week
  rules:
    - when: manual
