# Title: changelog/release.yml
#
# Description:
# This script is designed to generate and manage changelogs using git-cliff.
# It is used in a GitLab CI/CD pipeline.
# It consists of one main stage:
#     1. release: Generate the final changelog.
#
# Features:
#     - Generates a final changelog for the release using git-cliff.

include:
  - local: ".gitlab/ci/templates/changelog/common.yml"

stages:
  - release

generate_changelog_release:
  stage: release
  extends: .default_before_script
  script:
    - echo "📝 Generating final changelog..."

    - |
      if [ ! -f "$CLIFF_CONFIG_PATH" ]; then
        echo "❌ $CLIFF_CONFIG_PATH not found. Aborting."
        exit 1
      fi

    # Fetch main branch for comparison
    - echo "📥 Fetching origin/main..."
    - git fetch --depth=0 origin main

    # Generate final changelog
    - git-cliff --config $CLIFF_CONFIG_PATH  > $CHANGELOG_FILE
    - echo "📜 Final changelog generated in $CHANGELOG_FILE."

    # Commit & push updated CHANGELOG.md.
    - |
      if git diff --quiet $CHANGELOG_FILE; then
        echo "ℹ️ No changes in $CHANGELOG_FILE, skipping commit."
        exit 0
      fi
    - echo "📦 Committing changes..."
    - git add $CHANGELOG_FILE
    - |
      git commit -m "docs: update changelog for release [ci skip]"
    - |
      git push -o ci.skip origin HEAD:$CI_COMMIT_REF_NAME
    - echo "📦 Pushed changes to $CI_COMMIT_REF_NAME."
    - echo "✅ Changelog updated successfully."
    - echo "📌 Please review the final changelog."
  rules:
    - when: manual
