stages:
  - update_tag

variables:
  GIT_AUTHOR_NAME: "gitlab-ci"
  GIT_AUTHOR_EMAIL: "ci@example.com"
  CLIFF_CONFIG_PATH: ".gitlab/ci/config/.cliff.toml"

.default_before_script:
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - echo "📦 Tool Versions:"
    - git --version

    # set -euo pipefail: Exit immediately if a command exits with a non-zero status.
    - set -euo pipefail
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"

update_changelog_for_tag:
  stage: update_tag
  extends: .default_before_script
  script:
    - echo "🏷️ Updating changelog for new tag..."

    # Update CHANGELOG.md for the new tag
    - bash .gitlab/ci/scripts/changelog/update_tag.sh

    # Commit and push the updated changelog
    - echo "📦 Committing changes..."
    - LATEST_TAG=$(git describe --tags --abbrev=0)
    - git add CHANGELOG.md
    - git commit -m "docs: update changelog for tag $LATEST_TAG"
    - git push origin HEAD:$CI_COMMIT_REF_NAME

    - echo "🚀 Changelog updated successfully for tag $LATEST_TAG"
  rules:
    # Execute only when a new tag is created
    - if: $CI_COMMIT_TAG
      when: on_success
    # Manual trigger for other branches
    - when: manual
    # Skip otherwise
    - when: never
