# Title: changelog/update_tag.yml
#
# Description:
# This script is designed to update the changelog for a new tag.

include:
  - local: ".gitlab/ci/templates/changelog/common.yml"

stages:
  - update_tag

update_changelog_for_tag:
  stage: update_tag
  extends: .default_before_script
  script:
    - echo "🏷️ Updating changelog for new tag..."

    # Update CHANGELOG.md for the new tag
    - bash .gitlab/ci/scripts/changelog/update_tag.sh

    # Commit and push the updated changelog
    - echo "📦 Committing changes..."
    - LATEST_TAG=$(git describe --tags --abbrev=0)
    - git add CHANGELOG.md
    - git commit -m "docs: update changelog for tag $LATEST_TAG"
    - git push origin HEAD:$CI_COMMIT_REF_NAME

    - echo "🚀 Changelog updated successfully for tag $LATEST_TAG"
  rules:
    # Execute only when a new tag is created
    - if: $CI_COMMIT_TAG
      when: on_success
    # Manual trigger for other branches
    - when: manual
    # Skip otherwise
    - when: never
